server {
    listen 80;
    
    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        # 🌟 บรรทัดนี้คือเวทมนตร์ครับ: หาไฟล์ไม่เจอ ให้โยนกลับไป index.html
        try_files $uri $uri/ /index.html; 
    }
}